- name: Garantir que serviço do Zabbix está rodando
  community.docker.docker_container:
    name: zabbix-server
    image: zabbix/zabbix-server-pgsql:latest
    state: started
    ports:
      - "8081:8080"
    environment:
      DB_SERVER_HOST: zabbix-db
    restart_policy: always
